[[plugins]]
repo = 'drmingdrmer/vim-syntax-markdown'
on_ft = 'markdown'
hook_add = '''
    let g:markdown_fenced_languages = [
        \ 'cpp',
        \ 'haskell',
    \]
    highlight link markdownItalic NONE

    " This gets rid of the nasty _ italic bug in tpope's vim-markdown
    " block $$...$$
    syn region math start=/\$\$/ end=/\$\$/
    " inline math
    syn match math '\$[^$].\{-}\$'

    " actually highlight the region we defined as "math"
    hi link math Statement
  '''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'scss', 'sass']

[[plugins]]
repo = 'vmchale/dhall-vim'
on_ft = 'dhall'

[[plugins]]
repo = 'LumaKernel/coqpit.vim'
on_ft = 'coq'
hook_add = '''
    let g:coqpit_auto_launch=0
  '''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'h', 'cpp', 'hpp']

[[plugins]]
repo = 'alx741/vim-stylishask'
on_ft = ['haskell', 'idris', 'hs', 'hsc']
hook_add = '''
    let g:stylishask_on_save = 1
    let g:stylishask_config_file = "~/.vim/.stylish-haskell.yaml"
  '''

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = ['haskell', 'cabal', 'hs', 'hsc']
hook_add = '''
    let g:haskell_enable_quantification = 1   " to enable highlighting of `forall`
    let g:haskell_enable_recursivedo = 1      " to enable highlighting of `mdo` and `rec`
    let g:haskell_enable_arrowsyntax = 1      " to enable highlighting of `proc`
    let g:haskell_enable_pattern_synonyms = 1 " to enable highlighting of `pattern`
    let g:haskell_enable_typeroles = 1        " to enable highlighting of type roles
    let g:haskell_enable_static_pointers = 1  " to enable highlighting of `static`
    let g:haskell_backpack = 1                " to enable highlighting of backpack keywords
  '''

[[plugins]]
repo = 'idris-hackers/idris-vim'
on_ft = ['idris']

